# Generated by Django 2.1.5 on 2019-02-19 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('V1_0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concentrator_cls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Concentrator_id', models.TextField(default='', verbose_name='集中器唯一设备号')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_cls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terminal_id', models.TextField(default='', verbose_name='传感器唯一设备号')),
                ('Belong_Host', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='V1_0.Concentrator_cls')),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
