# Generated by Django 2.1.5 on 2019-02-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('V1_0', '0003_auto_20190220_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concentrator_cls',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='concentrator_cls',
            name='All_Truck_Space',
        ),
        migrations.RemoveField(
            model_name='concentrator_cls',
            name='Concentrator_id',
        ),
        migrations.RemoveField(
            model_name='concentrator_cls',
            name='Free_Truck_Space',
        ),
        migrations.RemoveField(
            model_name='concentrator_cls',
            name='Lat',
        ),
        migrations.RemoveField(
            model_name='concentrator_cls',
            name='Lng',
        ),
        migrations.RemoveField(
            model_name='concentrator_cls',
            name='Motify_Time',
        ),
        migrations.RemoveField(
            model_name='concentrator_cls',
            name='Price',
        ),
    ]
