# Generated by Django 2.1.5 on 2019-02-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('V1_0', '0006_auto_20190221_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concentrator_cls',
            old_name='Pnone',
            new_name='Phone',
        ),
    ]
