# Generated by Django 2.1.5 on 2019-02-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V1_0', '0008_auto_20190222_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concentrator_cls',
            name='Motify_Date',
        ),
        migrations.RemoveField(
            model_name='concentrator_cls',
            name='Motify_Time',
        ),
        migrations.AddField(
            model_name='concentrator_cls',
            name='Motify_DateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
